### ISSUE TITLE
onCheckout event order

### ISSUE THREAD

**Issue by randykato** [jeffharrell/minicart#239]
I've updated to v3.0.5 as it offers some additional functionality I needed, and I've got it almost all working.

I'm having an issue with cart.on('checkout'). I want to offer free shipping with a minimum order amount. I figured I should do this onCheckout rather than onAdd since quantities can be changed in the cart after the add event. I've got the checkout event function doing everything it needs to - checking subtotal and delivery zones and then changing the shipping charge to 0 if all criteria are met. I can see in the console when I view the items array that the shipping cost has indeed been changed to 0. BUT, when I'm redirected to PayPal, the shipping charge still shows up. It seems that checkout is compiling data before my function can change it, so it winds up sending the pre-altered data. If I go back, re-open the cart and checkout (without making any changes) it works with shipping = 0.

Am I understanding this properly? Or is something else going on? I would love to know if there's a way to refresh the cart data right before sending to PayPal...or if there's some other thing I'm not doing properly.

Cheers!
Randy

**Comment by jakeday** [comment]
I don't think the author ever posted a fix for this, but this is what he meant. I can do a pull request if needed. This fixes the issue.

 /**
  * Tells the view to redraw
  */
 View.prototype.redraw = function redraw() {
+    events.remove(this.el.querySelector('form'), 'submit', this.model.cart.checkout, this.model.cart);
     this.el.innerHTML = template(config.template, this.model);
+    events.add(this.el.querySelector('form'), 'submit', this.model.cart.checkout, this.model.cart);
 };
  
AND

     click: function (evt) {
         var target = evt.target,
             className = target.className;
 
         if (this.isShowing) {
-            // Cart checkout button
-            if (className === constants.SUBMIT_CLASS) {
-                this.model.cart.checkout(evt);
             // Cart close button
-            } else if (className === constants.CLOSER_CLASS) {
+            if (className === constants.CLOSER_CLASS) {
                 this.hide();
             // Product remove button
             } else if (className === constants.REMOVE_CLASS) {
                 this.model.cart.remove(target.getAttribute(constants.DATA_IDX));
             // Product quantity input

**Comment by jakeday** [comment]
Submitted the pull request.

**Comment by jeffharrell** [comment]
Thanks to the PR from @jakeday this should now be fixed as part of `3.0.6`.

**Comment by randykato** [comment]
I had kind of left this behind, but now I see it's been addressed. I've updated to v3.0.6, but I'm still getting the same behavior, so I'm thinking it must be my code:

```
paypal.minicart.cart.on('checkout', function (evt) {
    	if(paypal.minicart.cart.subtotal() >= 55) {
		alert("you get free shipping");
			paypal.minicart.cart._items[0].set('shipping',0);
		}
	}
});
```

I see that the shipping (which I've added only to the first item) is reset to 0 in the minicart, but it still shows up in PayPal. If I go back to the site and re-open the cart and checkout again, then the $0 shipping charge gets sent properly to PayPal.

Do I need to somehow manually force a data refresh before submitting to PayPal?

Thanks for any input.

Cheers!
Randy
